[package]
name = "gortsz"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = { version="1.0.1", default-features=false, features=[] }
heapless = "0.8.0"

[dev-dependencies]
const-str = "0.6.2"
